//! Build script for `quickvib-m300`.
//!
//! Does nothing at all in a normal build. With the non-default `bindgen` feature it regenerates
//! the FFI declaration snapshot from the vendor header and fails the build if the result differs
//! from what is committed, which is how SDK drift gets caught (`docs/M300-NATIVE.md` 4).

fn main() {
    println!("cargo:rerun-if-changed=build.rs");
    println!("cargo:rerun-if-env-changed=QUICKVIB_M300_HEADER");
    println!("cargo:rerun-if-env-changed=QUICKVIB_M300_SDK");

    #[cfg(feature = "bindgen")]
    bindings::generate();
}

/// Developer-bench only: `cargo build -p quickvib-m300 --features bindgen` on a machine that has
/// the SDK header and `libclang`. Never runs in CI.
#[cfg(feature = "bindgen")]
mod bindings {
    use std::path::{Path, PathBuf};

    /// Reviewed snapshot of the generated declarations, committed so the normal build needs
    /// neither `libclang` nor the vendor header. Absent until Phase 6 (blocked on Q-A).
    const SNAPSHOT: &str = "src/ffi_generated.rs";

    /// Header file name inside a `QUICKVIB_M300_SDK` directory. In the v1.2.0 distribution the
    /// headers live in `include/`, so `QUICKVIB_M300_SDK` should name that directory.
    const HEADER_NAME: &str = "m300.h";

    /// Sits beside `m300.h` and declares the setters that `cbindgen` could not see because they
    /// are generated by a Rust macro on the vendor's side (`docs/M300-NATIVE.md` §3). The ones
    /// QuickVib needs most — `m300_set_sample_rate`, `m300_set_data_type` — are only here.
    const MACROS_HEADER_NAME: &str = "m300_macros.h";

    /// The three prototypes `m300_macros.h` repeats with `struct M300ParamEntry *` instead of the
    /// anonymous-struct typedef `M300ParamEntry *` that `m300.h` uses. Including both headers in
    /// one translation unit is a clang error ("conflicting types"), so the wrapper renames the
    /// second declaration out of the way and the rename is blocklisted below. The real
    /// declarations still come from `m300.h`.
    const DUPLICATED_IN_MACROS_HEADER: [&str; 3] = [
        "m300_write_params",
        "m300_read_params",
        "m300_get_device_status",
    ];

    pub(crate) fn generate() {
        let header = header_path();
        println!("cargo:rerun-if-changed={}", header.display());

        let macros_header = header.with_file_name(MACROS_HEADER_NAME);
        if macros_header.is_file() {
            println!("cargo:rerun-if-changed={}", macros_header.display());
        } else {
            println!(
                "cargo:warning=bindgen: {} not found beside the main header; the macro-generated \
                 setters (m300_set_sample_rate, m300_set_data_type, ...) will be missing",
                macros_header.display()
            );
        }

        let mut builder = bindgen::Builder::default()
            .header_contents("quickvib_m300_wrapper.h", &wrapper_source(&header, &macros_header))
            .clang_arg(format!("-I{}", parent_dir(&header).display()))
            // Bind the vendor's surface and nothing else: every extra declaration is another
            // chance to get the ABI wrong (docs/M300-NATIVE.md 3).
            .allowlist_function("^m300_.*")
            .allowlist_type("^(M300|Mqtt|Net|Server|C[A-Z]).*")
            .allowlist_var(
                "^(M300_|SEND_PORT|RECV_PORT|HEADER_SIZE|CRC_SIZE|MAX_PAYLOAD|PROTOCOL_VERSION|MAX_FW_FRAME|VERSION_).*",
            )
            .generate_comments(true)
            .layout_tests(false)
            .parse_callbacks(Box::new(bindgen::CargoCallbacks::new()));

        for name in DUPLICATED_IN_MACROS_HEADER {
            builder = builder.blocklist_function(format!("^{name}_duplicate_decl$"));
        }

        let generated = match builder.generate() {
            Ok(bindings) => bindings.to_string(),
            Err(err) => panic!("bindgen failed on {}: {err}", header.display()),
        };

        let out_dir = match std::env::var_os("OUT_DIR") {
            Some(dir) => PathBuf::from(dir),
            None => panic!("OUT_DIR is not set; this is not a cargo build"),
        };
        let fresh = out_dir.join("ffi_generated.rs");
        if let Err(err) = std::fs::write(&fresh, &generated) {
            panic!("could not write {}: {err}", fresh.display());
        }

        compare_with_snapshot(&generated, &fresh);
    }

    /// Fail loudly on drift rather than silently rewriting reviewed source: the snapshot is the
    /// declaration set a human checked against the header, so a change to it is a review event.
    fn compare_with_snapshot(generated: &str, fresh: &Path) {
        let snapshot = Path::new(SNAPSHOT);
        match std::fs::read_to_string(snapshot) {
            Ok(committed) if committed == generated => {
                println!("cargo:warning=bindgen: {SNAPSHOT} is up to date with the SDK header");
            }
            Ok(_) => panic!(
                "bindgen: {SNAPSHOT} differs from the declarations generated from the SDK header. \
                 Review the difference, then copy {} over it and commit the change.",
                fresh.display()
            ),
            Err(_) => println!(
                "cargo:warning=bindgen: {SNAPSHOT} does not exist yet. Review {} and commit it as \
                 the reviewed snapshot (docs/M300-NATIVE.md 4).",
                fresh.display()
            ),
        }
    }

    /// One translation unit over both vendor headers, with the duplicated prototypes renamed so
    /// clang stops at neither of them.
    fn wrapper_source(header: &Path, macros_header: &Path) -> String {
        let mut source = format!("#include \"{}\"\n", header.display());
        if macros_header.is_file() {
            for name in DUPLICATED_IN_MACROS_HEADER {
                source.push_str(&format!("#define {name} {name}_duplicate_decl\n"));
            }
            source.push_str(&format!("#include \"{}\"\n", macros_header.display()));
            for name in DUPLICATED_IN_MACROS_HEADER {
                source.push_str(&format!("#undef {name}\n"));
            }
        }
        source
    }

    fn parent_dir(header: &Path) -> &Path {
        header.parent().unwrap_or(Path::new("."))
    }

    fn header_path() -> PathBuf {
        if let Some(path) = std::env::var_os("QUICKVIB_M300_HEADER") {
            return PathBuf::from(path);
        }
        if let Some(dir) = std::env::var_os("QUICKVIB_M300_SDK") {
            return Path::new(&dir).join(HEADER_NAME);
        }
        panic!(
            "the `bindgen` feature needs the SDK header: set QUICKVIB_M300_HEADER to the full \
             path of {HEADER_NAME}, or QUICKVIB_M300_SDK to the directory containing it"
        );
    }
}
