/* automatically generated by rust-bindgen 0.70.1 */

pub const VERSION_MAJOR: u32 = 1;
pub const VERSION_MINOR: u32 = 2;
pub const VERSION_PATCH: u32 = 0;
pub const M300_OK: u32 = 0;
pub const M300_FAIL: u32 = 1;
pub const SEND_PORT: u32 = 9222;
pub const RECV_PORT: u32 = 9223;
pub const HEADER_SIZE: u32 = 18;
pub const CRC_SIZE: u32 = 4;
pub const MAX_PAYLOAD: u32 = 512;
pub const PROTOCOL_VERSION: u32 = 0;
pub const MAX_FW_FRAME: u32 = 1280;
pub const M300NcResult_M300_NC_RESULT_OK: M300NcResult = 0;
pub const M300NcResult_M300_NC_RESULT_ERR_INVALID_ARG: M300NcResult = -1;
pub const M300NcResult_M300_NC_RESULT_ERR_BUFFER_SMALL: M300NcResult = -2;
pub const M300NcResult_M300_NC_RESULT_ERR_BAD_HEADER: M300NcResult = -3;
pub const M300NcResult_M300_NC_RESULT_ERR_CRC_MISMATCH: M300NcResult = -4;
pub const M300NcResult_M300_NC_RESULT_ERR_BAD_PACKET: M300NcResult = -5;
pub const M300NcResult_M300_NC_RESULT_ERR_NETWORK: M300NcResult = -6;
pub const M300NcResult_M300_NC_RESULT_ERR_TIMEOUT: M300NcResult = -7;
pub type M300NcResult = i32;
#[doc = " 成功"]
pub const M300Result_M300_RESULT_SUCCESS: M300Result = 0;
#[doc = " 参数无效（NULL、非法值）"]
pub const M300Result_M300_RESULT_ERR_INVALID_ARG: M300Result = -1;
#[doc = " 输出缓冲区不足"]
pub const M300Result_M300_RESULT_ERR_BUFFER_SMALL: M300Result = -2;
#[doc = " 协议头不匹配"]
pub const M300Result_M300_RESULT_ERR_BAD_HEADER: M300Result = -3;
#[doc = " CRC 校验失败"]
pub const M300Result_M300_RESULT_ERR_CRC_MISMATCH: M300Result = -4;
#[doc = " 包格式或长度错误"]
pub const M300Result_M300_RESULT_ERR_BAD_PACKET: M300Result = -5;
#[doc = " 等待设备应答超时"]
pub const M300Result_M300_RESULT_ERR_TIMEOUT: M300Result = -6;
#[doc = " 网络层错误"]
pub const M300Result_M300_RESULT_ERR_NETWORK: M300Result = -7;
#[doc = " 设备未连接或已断开"]
pub const M300Result_M300_RESULT_ERR_DISCONNECTED: M300Result = -8;
pub type M300Result = i32;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct MqttConfig {
    _unused: [u8; 0],
}
pub type M300DeviceHandle = *mut ::std::os::raw::c_void;
#[doc = " 硬件与网络信息。\n\n 用 `#[repr(C)]` 保证与旧 SDK 同名结构体字段顺序、对齐一致。"]
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct M300HardwareInfo {
    pub device_type: u8,
    pub ip: [u8; 4usize],
    pub subnet: [u8; 4usize],
    pub gateway: [u8; 4usize],
    pub mac: [u8; 6usize],
    #[doc = " 序列号（ASCII，可能不带 NUL 结尾）。"]
    pub serial: [u8; 10usize],
    pub fpga_version: [u8; 4usize],
    pub bootloader_version: [u8; 3usize],
    pub app_version: [u8; 3usize],
    pub server_ip: [u8; 4usize],
    pub server_port: u16,
    #[doc = " 非 0 表示 fpga_version 字段有效（兼容短格式应答）。"]
    pub has_fpga_version: u8,
}
#[doc = " 参数键值对。固定 64 字节 value 字段——足够覆盖所有 SDK 参数。"]
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct M300ParamEntry {
    pub id: u32,
    pub length: u32,
    pub value: [u8; 64usize],
}
pub type CDataCallback = ::std::option::Option<
    unsafe extern "C" fn(
        device: M300DeviceHandle,
        data_type: u32,
        point_count: u32,
        data: *const u8,
        data_len: u32,
        user_data: *mut ::std::os::raw::c_void,
    ),
>;
pub type CUpgradeRequestCallback = ::std::option::Option<
    unsafe extern "C" fn(device: M300DeviceHandle, user_data: *mut ::std::os::raw::c_void),
>;
pub type CUpgradeResultCallback = ::std::option::Option<
    unsafe extern "C" fn(
        device: M300DeviceHandle,
        result_code: u16,
        user_data: *mut ::std::os::raw::c_void,
    ),
>;
pub type CFirmwareProgressCallback = ::std::option::Option<
    unsafe extern "C" fn(
        transferred: u32,
        total: u32,
        user_data: *mut ::std::os::raw::c_void,
    ) -> i32,
>;
pub type M300NcHandle = *mut ::std::os::raw::c_void;
#[doc = " Device info reported by `query_device_info` (0x10).\n\n Field order / types are kept **byte-for-byte ABI compatible** with the\n legacy C SDK's `M300NcDeviceInfo` (see `m300_net_conf.h`), so downstream\n apps that call `m300_nc_discover` into an `M300NcDeviceInfo[]` keep working\n unchanged after switching to the Rust SDK.\n\n Note: this is the *in-memory struct* layout (with natural C alignment), not\n the on-wire layout. The wire payload is densely packed (no padding); see\n [`parse_device_info`] for the wire offsets."]
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct NetConfig {
    pub device_type: u8,
    pub ip: [u8; 4usize],
    pub subnet: [u8; 4usize],
    pub gateway: [u8; 4usize],
    pub mac: [u8; 6usize],
    pub serial: [u8; 10usize],
    pub bootloader_version: [u8; 3usize],
    pub app_version: [u8; 3usize],
    pub server_ip: [u8; 4usize],
    pub server_port: u16,
    pub broker_ip: [u8; 4usize],
    pub broker_port: u16,
    pub transport_mode: u8,
    pub username: [u8; 64usize],
    pub password: [u8; 64usize],
    pub sub_topic: [u8; 128usize],
    pub mqtt_ssl_enable: u8,
    pub time_sync_mode: u8,
    pub manual_time_utc_unix: u32,
    pub ntp_server: [u8; 128usize],
    pub mqtt_ssl_cert_installed: u8,
    pub dns_primary: [u8; 4usize],
    pub dns_secondary: [u8; 4usize],
    pub ignore_time_sync: u8,
    pub auto_upload_on_boot: u8,
}
#[doc = " Network configuration payload (matches `M300NcNetworkConfig` wire layout, 20 bytes)."]
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct NetworkConfig {
    pub ip: [u8; 4usize],
    pub subnet: [u8; 4usize],
    pub gateway: [u8; 4usize],
    pub dns_primary: [u8; 4usize],
    pub dns_secondary: [u8; 4usize],
}
#[doc = " Server endpoint config (TCP target the device reaches out to)."]
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct ServerConfig {
    pub server_ip: [u8; 4usize],
    pub server_port: u16,
}
#[doc = " Opaque pointer type for the C ABI."]
pub type M300Server = *mut ::std::os::raw::c_void;
pub type CConnectCallback = ::std::option::Option<
    unsafe extern "C" fn(
        server: M300Server,
        device: M300DeviceHandle,
        user_data: *mut ::std::os::raw::c_void,
    ),
>;
pub type CDisconnectCallback = ::std::option::Option<
    unsafe extern "C" fn(
        server: M300Server,
        device: M300DeviceHandle,
        user_data: *mut ::std::os::raw::c_void,
    ),
>;
extern "C" {
    pub fn m300_start_acquisition(
        device: M300DeviceHandle,
        result_code: *mut u16,
        timeout_ms: u32,
    ) -> M300Result;
}
extern "C" {
    pub fn m300_stop_acquisition(
        device: M300DeviceHandle,
        result_code: *mut u16,
        timeout_ms: u32,
    ) -> M300Result;
}
extern "C" {
    pub fn m300_remove_dc(
        device: M300DeviceHandle,
        result_code: *mut u16,
        timeout_ms: u32,
    ) -> M300Result;
}
extern "C" {
    pub fn m300_set_iq_correct_mode(
        device: M300DeviceHandle,
        mode: u8,
        result_code: *mut u16,
        timeout_ms: u32,
    ) -> M300Result;
}
extern "C" {
    pub fn m300_set_segment_length(
        device: M300DeviceHandle,
        length: i32,
        result_code: *mut u16,
        timeout_ms: u32,
    ) -> M300Result;
}
extern "C" {
    pub fn m300_get_sample_rate(
        device: M300DeviceHandle,
        rate: *mut u8,
        result_code: *mut u16,
        timeout_ms: u32,
    ) -> M300Result;
}
extern "C" {
    pub fn m300_get_data_type(
        device: M300DeviceHandle,
        t: *mut u8,
        result_code: *mut u16,
        timeout_ms: u32,
    ) -> M300Result;
}
extern "C" {
    pub fn m300_get_running_status(
        device: M300DeviceHandle,
        status: *mut u8,
        result_code: *mut u16,
        timeout_ms: u32,
    ) -> M300Result;
}
extern "C" {
    pub fn m300_get_board_temp(
        device: M300DeviceHandle,
        temp: *mut f32,
        result_code: *mut u16,
        timeout_ms: u32,
    ) -> M300Result;
}
extern "C" {
    pub fn m300_get_signal_strength(
        device: M300DeviceHandle,
        sig_i: *mut i16,
        sig_q: *mut i16,
        result_code: *mut u16,
        timeout_ms: u32,
    ) -> M300Result;
}
extern "C" {
    pub fn m300_get_hardware_info(
        device: M300DeviceHandle,
        info: *mut M300HardwareInfo,
        result_code: *mut u16,
        timeout_ms: u32,
    ) -> M300Result;
}
extern "C" {
    pub fn m300_set_trigger_level(
        device: M300DeviceHandle,
        level: f32,
        result_code: *mut u16,
        timeout_ms: u32,
    ) -> M300Result;
}
extern "C" {
    pub fn m300_set_trigger_channel(
        device: M300DeviceHandle,
        channel: u8,
        result_code: *mut u16,
        timeout_ms: u32,
    ) -> M300Result;
}
extern "C" {
    pub fn m300_set_trigger_data_length(
        device: M300DeviceHandle,
        length: u32,
        result_code: *mut u16,
        timeout_ms: u32,
    ) -> M300Result;
}
extern "C" {
    pub fn m300_set_trigger_pre_points(
        device: M300DeviceHandle,
        points: u32,
        result_code: *mut u16,
        timeout_ms: u32,
    ) -> M300Result;
}
extern "C" {
    pub fn m300_start_pulse(
        device: M300DeviceHandle,
        param1: i32,
        param2: i32,
        param3: i32,
        result_code: *mut u16,
        timeout_ms: u32,
    ) -> M300Result;
}
extern "C" {
    pub fn m300_stop_pulse(
        device: M300DeviceHandle,
        result_code: *mut u16,
        timeout_ms: u32,
    ) -> M300Result;
}
extern "C" {
    pub fn m300_get_laser_current(
        device: M300DeviceHandle,
        current_ma: *mut f32,
        result_code: *mut u16,
        timeout_ms: u32,
    ) -> M300Result;
}
extern "C" {
    pub fn m300_get_tec_temp(
        device: M300DeviceHandle,
        temp_celsius: *mut f32,
        result_code: *mut u16,
        timeout_ms: u32,
    ) -> M300Result;
}
extern "C" {
    pub fn m300_set_pid(
        device: M300DeviceHandle,
        p: f32,
        i: f32,
        d: f32,
        result_code: *mut u16,
        timeout_ms: u32,
    ) -> M300Result;
}
extern "C" {
    pub fn m300_write_params(
        device: M300DeviceHandle,
        params: *const M300ParamEntry,
        count: u32,
        result_code: *mut u16,
        timeout_ms: u32,
    ) -> M300Result;
}
extern "C" {
    pub fn m300_read_params(
        device: M300DeviceHandle,
        param_ids: *const u32,
        id_count: u32,
        out_params: *mut M300ParamEntry,
        max_params: u32,
        out_count: *mut u32,
        result_code: *mut u16,
        timeout_ms: u32,
    ) -> M300Result;
}
extern "C" {
    pub fn m300_get_param_id_list(
        device: M300DeviceHandle,
        ids: *mut u32,
        max_ids: u32,
        count: *mut u32,
        result_code: *mut u16,
        timeout_ms: u32,
    ) -> M300Result;
}
extern "C" {
    pub fn m300_get_device_status(
        device: M300DeviceHandle,
        status_ids: *const u32,
        id_count: u32,
        out_entries: *mut M300ParamEntry,
        max_entries: u32,
        out_count: *mut u32,
        result_code: *mut u16,
        timeout_ms: u32,
    ) -> M300Result;
}
extern "C" {
    pub fn m300_parse_hardware_info(
        data: *const u8,
        data_len: u32,
        info: *mut M300HardwareInfo,
    ) -> M300Result;
}
extern "C" {
    pub fn m300_device_get_addr(
        device: M300DeviceHandle,
        buf: *mut ::std::os::raw::c_char,
        buf_len: u32,
    ) -> *const ::std::os::raw::c_char;
}
extern "C" {
    pub fn m300_device_get_port(device: M300DeviceHandle) -> u16;
}
extern "C" {
    pub fn m300_device_is_connected(device: M300DeviceHandle) -> i32;
}
extern "C" {
    pub fn m300_device_disconnect(device: M300DeviceHandle);
}
extern "C" {
    pub fn m300_device_set_data_callback(
        device: M300DeviceHandle,
        cb: CDataCallback,
        user_data: *mut ::std::os::raw::c_void,
    );
}
extern "C" {
    pub fn m300_device_set_upgrade_request_callback(
        device: M300DeviceHandle,
        cb: CUpgradeRequestCallback,
        user_data: *mut ::std::os::raw::c_void,
    );
}
extern "C" {
    pub fn m300_device_set_upgrade_result_callback(
        device: M300DeviceHandle,
        cb: CUpgradeResultCallback,
        user_data: *mut ::std::os::raw::c_void,
    );
}
extern "C" {
    pub fn m300_device_set_user_data(
        device: M300DeviceHandle,
        user_data: *mut ::std::os::raw::c_void,
    );
}
extern "C" {
    pub fn m300_device_get_user_data(device: M300DeviceHandle) -> *mut ::std::os::raw::c_void;
}
extern "C" {
    pub fn m300_start_upgrade(
        device: M300DeviceHandle,
        result_code: *mut u16,
        timeout_ms: u32,
    ) -> M300Result;
}
extern "C" {
    pub fn m300_send_firmware_param(
        device: M300DeviceHandle,
        encrypted_crc: u32,
        firmware_size: u32,
        result_code: *mut u16,
        timeout_ms: u32,
    ) -> M300Result;
}
extern "C" {
    pub fn m300_transfer_firmware(
        device: M300DeviceHandle,
        firmware: *const u8,
        firmware_size: u32,
        timeout_ms: u32,
    ) -> M300Result;
}
extern "C" {
    pub fn m300_transfer_firmware_ex(
        device: M300DeviceHandle,
        firmware: *const u8,
        firmware_size: u32,
        timeout_ms: u32,
        progress_cb: CFirmwareProgressCallback,
        progress_user: *mut ::std::os::raw::c_void,
    ) -> M300Result;
}
extern "C" {
    pub fn m300_firmware_encrypt_crc(firmware: *const u8, firmware_size: u32) -> u32;
}
extern "C" {
    pub fn m300_nc_create(handle: *mut M300NcHandle, timeout_ms: u32) -> M300NcResult;
}
extern "C" {
    pub fn m300_nc_create_ex(
        handle: *mut M300NcHandle,
        timeout_ms: u32,
        bind_ip: *const ::std::os::raw::c_char,
    ) -> M300NcResult;
}
extern "C" {
    pub fn m300_nc_destroy(handle: M300NcHandle);
}
extern "C" {
    #[doc = " 设备发现：返回找到的设备数；写入 `out_devices` 数组（最多 `max_devices`）。"]
    pub fn m300_nc_discover(
        handle: M300NcHandle,
        out_devices: *mut NetConfig,
        max_devices: u32,
        out_count: *mut u32,
    ) -> M300NcResult;
}
extern "C" {
    pub fn m300_nc_set_network(
        handle: M300NcHandle,
        mac: *const u8,
        config: *const NetworkConfig,
        out_status: *mut u8,
    ) -> M300NcResult;
}
extern "C" {
    pub fn m300_nc_set_server(
        handle: M300NcHandle,
        mac: *const u8,
        config: *const ServerConfig,
        out_status: *mut u8,
    ) -> M300NcResult;
}
extern "C" {
    pub fn m300_nc_restart(
        handle: M300NcHandle,
        mac: *const u8,
        out_status: *mut u8,
    ) -> M300NcResult;
}
extern "C" {
    pub fn m300_nc_restore_factory(
        handle: M300NcHandle,
        mac: *const u8,
        out_status: *mut u8,
    ) -> M300NcResult;
}
extern "C" {
    pub fn m300_nc_set_auto_upload(
        handle: M300NcHandle,
        mac: *const u8,
        enable: u8,
        out_status: *mut u8,
    ) -> M300NcResult;
}
extern "C" {
    pub fn m300_nc_set_transport_mode(
        handle: M300NcHandle,
        mac: *const u8,
        transport_mode: u8,
        out_status: *mut u8,
    ) -> M300NcResult;
}
extern "C" {
    pub fn m300_nc_set_sn(
        handle: M300NcHandle,
        mac: *const u8,
        sn_code: *const u8,
        out_status: *mut u8,
    ) -> M300NcResult;
}
extern "C" {
    pub fn m300_nc_set_mac(
        handle: M300NcHandle,
        mac: *const u8,
        new_mac: *const u8,
        out_status: *mut u8,
    ) -> M300NcResult;
}
extern "C" {
    pub fn m300_nc_set_mqtt(
        handle: M300NcHandle,
        mac: *const u8,
        config: *const MqttConfig,
        out_status: *mut u8,
    ) -> M300NcResult;
}
extern "C" {
    pub fn m300_nc_set_mqtt_ssl_cert(
        handle: M300NcHandle,
        mac: *const u8,
        cert_pem: *const u8,
        cert_len: u32,
        out_status: *mut u8,
    ) -> M300NcResult;
}
extern "C" {
    pub fn m300_server_create(port: u16, out_server: *mut M300Server) -> M300Result;
}
extern "C" {
    #[doc = " 创建服务端并指定绑定地址（如 \"192.168.1.100\"）。\n `bind_addr` 为 NULL 或空串时等同于 `m300_server_create`（绑定所有网卡）。"]
    pub fn m300_server_create_ex(
        bind_addr: *const ::std::os::raw::c_char,
        port: u16,
        out_server: *mut M300Server,
    ) -> M300Result;
}
extern "C" {
    pub fn m300_server_destroy(server: M300Server);
}
extern "C" {
    pub fn m300_server_set_connect_callback(
        server: M300Server,
        cb: CConnectCallback,
        user_data: *mut ::std::os::raw::c_void,
    );
}
extern "C" {
    pub fn m300_server_set_disconnect_callback(
        server: M300Server,
        cb: CDisconnectCallback,
        user_data: *mut ::std::os::raw::c_void,
    );
}
extern "C" {
    pub fn m300_server_set_auto_read_sample_rate(server: M300Server, enable: i32, timeout_ms: u32);
}
extern "C" {
    pub fn m300_server_start(server: M300Server) -> M300Result;
}
extern "C" {
    pub fn m300_server_stop(server: M300Server);
}
extern "C" {
    pub fn m300_server_device_count(server: M300Server) -> u32;
}
extern "C" {
    pub fn m300_server_get_devices(
        server: M300Server,
        devices: *mut M300DeviceHandle,
        max_count: u32,
    ) -> u32;
}
extern "C" {
    #[doc = " Free a device handle returned by [`m300_server_get_devices`] / connect cb.\n 这是 Rust 端新增的 API（旧 C SDK 设备句柄是裸指针、不需要释放——但是\n 在 Rust 实现里，每个 handle 都对应一个 Box<Arc<Device>>，不释放会泄漏）。"]
    pub fn m300_device_release_handle(device: M300DeviceHandle);
}
extern "C" {
    #[doc = " SDK 版本字符串（如 `\"1.2.0\"`）。返回静态指针，调用方不要 free。\n\n 用 `\\0` 结尾的字节字面量，保证 CStr::from_bytes_with_nul 不会失败。"]
    pub fn m300_sdk_version() -> *const ::std::os::raw::c_char;
}
extern "C" {
    #[doc = " SDK 数值版本号。任何输出指针可以为 NULL。"]
    pub fn m300_sdk_version_numbers(
        major: *mut ::std::os::raw::c_int,
        minor: *mut ::std::os::raw::c_int,
        patch: *mut ::std::os::raw::c_int,
    );
}
extern "C" {
    #[doc = " SDK 全局初始化（可选；幂等；引用计数管理）。"]
    pub fn m300_init() -> M300Result;
}
extern "C" {
    #[doc = " 与 [`m300_init`] 配对；引用计数归零后释放资源。"]
    pub fn m300_cleanup();
}
pub type M300Device = M300DeviceHandle;
pub type M300DataCallback = CDataCallback;
pub type M300UpgradeRequestCallback = CUpgradeRequestCallback;
pub type M300UpgradeResultCallback = CUpgradeResultCallback;
pub type M300ConnectCallback = CConnectCallback;
pub type M300DisconnectCallback = CDisconnectCallback;
extern "C" {
    pub fn m300_set_laser_level(
        device: M300Device,
        level: u8,
        result_code: *mut u16,
        timeout_ms: u32,
    ) -> M300Result;
}
extern "C" {
    pub fn m300_set_low_pass_filter(
        device: M300Device,
        lpf: u8,
        result_code: *mut u16,
        timeout_ms: u32,
    ) -> M300Result;
}
extern "C" {
    pub fn m300_set_velocity_range(
        device: M300Device,
        range: u8,
        result_code: *mut u16,
        timeout_ms: u32,
    ) -> M300Result;
}
extern "C" {
    pub fn m300_set_displacement_range(
        device: M300Device,
        range: u8,
        result_code: *mut u16,
        timeout_ms: u32,
    ) -> M300Result;
}
extern "C" {
    pub fn m300_set_acceleration_range(
        device: M300Device,
        range: u8,
        result_code: *mut u16,
        timeout_ms: u32,
    ) -> M300Result;
}
extern "C" {
    pub fn m300_set_digital_range(
        device: M300Device,
        range: u8,
        result_code: *mut u16,
        timeout_ms: u32,
    ) -> M300Result;
}
extern "C" {
    pub fn m300_set_analog_out1_type(
        device: M300Device,
        type_: u8,
        result_code: *mut u16,
        timeout_ms: u32,
    ) -> M300Result;
}
extern "C" {
    pub fn m300_set_front_filter(
        device: M300Device,
        filter: u8,
        result_code: *mut u16,
        timeout_ms: u32,
    ) -> M300Result;
}
extern "C" {
    pub fn m300_set_front_filter_alg(
        device: M300Device,
        alg: u8,
        result_code: *mut u16,
        timeout_ms: u32,
    ) -> M300Result;
}
extern "C" {
    pub fn m300_set_analog_out1_switch(
        device: M300Device,
        on_off: u8,
        result_code: *mut u16,
        timeout_ms: u32,
    ) -> M300Result;
}
extern "C" {
    pub fn m300_set_front_filter_switch(
        device: M300Device,
        on_off: u8,
        result_code: *mut u16,
        timeout_ms: u32,
    ) -> M300Result;
}
extern "C" {
    pub fn m300_set_dc_remove_switch(
        device: M300Device,
        on_off: u8,
        result_code: *mut u16,
        timeout_ms: u32,
    ) -> M300Result;
}
extern "C" {
    pub fn m300_set_iq_correct_switch(
        device: M300Device,
        on_off: u8,
        result_code: *mut u16,
        timeout_ms: u32,
    ) -> M300Result;
}
extern "C" {
    pub fn m300_set_vel_lpf_switch(
        device: M300Device,
        on_off: u8,
        result_code: *mut u16,
        timeout_ms: u32,
    ) -> M300Result;
}
extern "C" {
    pub fn m300_set_disp_lpf_switch(
        device: M300Device,
        on_off: u8,
        result_code: *mut u16,
        timeout_ms: u32,
    ) -> M300Result;
}
extern "C" {
    pub fn m300_set_acc_lpf_switch(
        device: M300Device,
        on_off: u8,
        result_code: *mut u16,
        timeout_ms: u32,
    ) -> M300Result;
}
extern "C" {
    pub fn m300_set_iq_correct_alpha(
        device: M300Device,
        alpha: f32,
        result_code: *mut u16,
        timeout_ms: u32,
    ) -> M300Result;
}
extern "C" {
    pub fn m300_set_vel_amp_correct(
        device: M300Device,
        value: f32,
        result_code: *mut u16,
        timeout_ms: u32,
    ) -> M300Result;
}
extern "C" {
    pub fn m300_set_disp_amp_correct(
        device: M300Device,
        value: f32,
        result_code: *mut u16,
        timeout_ms: u32,
    ) -> M300Result;
}
extern "C" {
    pub fn m300_set_acc_amp_correct(
        device: M300Device,
        value: f32,
        result_code: *mut u16,
        timeout_ms: u32,
    ) -> M300Result;
}
extern "C" {
    pub fn m300_get_laser_level(
        device: M300Device,
        level: *mut u8,
        result_code: *mut u16,
        timeout_ms: u32,
    ) -> M300Result;
}
extern "C" {
    pub fn m300_get_low_pass_filter(
        device: M300Device,
        lpf: *mut u8,
        result_code: *mut u16,
        timeout_ms: u32,
    ) -> M300Result;
}
extern "C" {
    pub fn m300_get_velocity_range(
        device: M300Device,
        range: *mut u8,
        result_code: *mut u16,
        timeout_ms: u32,
    ) -> M300Result;
}
extern "C" {
    pub fn m300_get_displacement_range(
        device: M300Device,
        range: *mut u8,
        result_code: *mut u16,
        timeout_ms: u32,
    ) -> M300Result;
}
extern "C" {
    pub fn m300_get_acceleration_range(
        device: M300Device,
        range: *mut u8,
        result_code: *mut u16,
        timeout_ms: u32,
    ) -> M300Result;
}
extern "C" {
    pub fn m300_get_digital_range(
        device: M300Device,
        range: *mut u8,
        result_code: *mut u16,
        timeout_ms: u32,
    ) -> M300Result;
}
extern "C" {
    pub fn m300_set_high_pass_filter(
        device: M300Device,
        hpf: u8,
        result_code: *mut u16,
        timeout_ms: u32,
    ) -> M300Result;
}
extern "C" {
    pub fn m300_get_high_pass_filter(
        device: M300Device,
        hpf: *mut u8,
        result_code: *mut u16,
        timeout_ms: u32,
    ) -> M300Result;
}
extern "C" {
    pub fn m300_set_analog_out2_type(
        device: M300Device,
        type_: u8,
        result_code: *mut u16,
        timeout_ms: u32,
    ) -> M300Result;
}
extern "C" {
    pub fn m300_set_analog_out2_switch(
        device: M300Device,
        on_off: u8,
        result_code: *mut u16,
        timeout_ms: u32,
    ) -> M300Result;
}
extern "C" {
    pub fn m300_set_trigger_type(
        device: M300Device,
        type_: u8,
        result_code: *mut u16,
        timeout_ms: u32,
    ) -> M300Result;
}
extern "C" {
    pub fn m300_get_trigger_type(
        device: M300Device,
        type_: *mut u8,
        result_code: *mut u16,
        timeout_ms: u32,
    ) -> M300Result;
}
extern "C" {
    pub fn m300_set_trigger_edge(
        device: M300Device,
        edge: u8,
        result_code: *mut u16,
        timeout_ms: u32,
    ) -> M300Result;
}
extern "C" {
    pub fn m300_set_laser_current(
        device: M300Device,
        current_mA: f32,
        result_code: *mut u16,
        timeout_ms: u32,
    ) -> M300Result;
}
extern "C" {
    pub fn m300_set_tec_temp(
        device: M300Device,
        temp_celsius: f32,
        result_code: *mut u16,
        timeout_ms: u32,
    ) -> M300Result;
}
